apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: nginx
      image: nginx:latest
      startupProbe:
        exec:
          command:
            - cat
            - /tmp/startup_complete
        periodSeconds: 10
        failureThreshold: 60
        successThreshold: 1
      resources:
        limits:
          cpu: 100m
          memory: 240Mi