apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: atlaseks-pod-reader-cr
rules:
- apiGroups: [""]
  resources: ["pods", "nodes"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "watch", "list", "create", "update", "delete"]