apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::590183762151:role/tfeksnodegrouprolename
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: arn:aws:iam::590183762151:user/atlaseks
      username: atlaseks
      groups: []
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system