apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: eks-chase-ns-admin-rb
subjects:
- kind: User
  name: atlaseks
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: chase-ns-admin
  apiGroup: rbac.authorization.k8s.io