apiVersion: v1
kind: Pod
metadata:
  name: nginx-readiness-probe-http
spec:
  containers:
  - name: nginx-readiness-probe-http
    image: nginx-readiness-image-http
    ports:
      - containerPort: 80
    readinessProbe:
      httpGet:
        path: /healthz
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 10
      failureThreshold: 3
      successThreshold: 1
    resources:
      limits:
        memory: 128Mi
        cpu: 500m
