apiVersion: v1
kind: Pod
metadata:
  name: nginx-readiness-probe-exec
spec:
  containers:
  - name: nginx-readiness-probe-exec
    image: nginx-readiness-image-exec
    ports:
      - containerPort: 80
    readinessProbe:
      exec:
        command:
          - "/bin/sh"
          - "-c"
          - "curl --silent --fail http://localhost:80/healthz"
      initialDelaySeconds: 5
      periodSeconds: 10
      failureThreshold: 3
      successThreshold: 1
    resources:
      limits:
        memory: 128Mi
        cpu: 500m