apiVersion: v1
kind: PersistentVolume
metadata:
  name: eks-pv
spec:
  storageClass: ""
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  mountOptions:
    - soft
    - nfsvers=4.1
    - retrans=3
  nfs:
    path: "/mnt/data"
    server: 172.17.0.2