apiVersion: v1
kind: Pod
metadata:
  name: nginx-readiness-probe-tcp
spec:
  containers:
  - name: nginx-readiness-probe-tcp
    image: nginx-readiness-image-tcp
    ports:
      - containerPort: 80
    readinessProbe:
      tcpSocket:
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 10
      failureThreshold: 3
      successThreshold: 1
    resources:
      limits:
        memory: 128Mi
        cpu: 500m