apiVersion: v1
kind: Pod
metadata:
  name: nginx-liveness-pod
spec:
  containers:
  - name: nginx-liveness-pod
    image: nginx-liveness-image
    livenessProbe:
      exec:
        command:
          - "/bin/sh"
          - "-c"
          - "curl --silent --fail http://localhost:80/healthz"
      initialDelaySeconds: 15
      periodSeconds: 20
      failureThreshold: 3
      successThreshold: 1
    resources:
      limits:
        memory: 128Mi
        cpu: 500m