apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport-service
  namespace: web
spec:
  selector:
    web: nginx
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30001