apiVersion: v1
kind: Pod
metadata:
  name: nginx-liveness-pod
spec:
  containers:
  - name: nginx-liveness-pod
    image: nginx-liveness-image
    livenessProbe:
      tcpSocket:
        port: 8080 
      initialDelaySeconds: 15
      periodSeconds: 10
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80