apiVersion: v1
kind: Pod
metadata:
  name: nginx-readiness-pod
spec:
  containers:
  - name: nginx-readiness-pod
    image: nginx-readiness-image
    readinessProbe:
      httpGet:
        path: /healthz
        port: 80
      initialDelaySeconds: 15
      periodSeconds: 10
    resources:
      limits:
        memory: 128Mi
        cpu: 500m
    ports:
      - containerPort: 80