apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
      startupProbe:
        tcpSocket:
          port: 80
        periodSeconds: 10
        failureThreshold: 30
        successThreshold: 1
      readinessProbe:
        tcpSocket:
          port: 80
        initialDelaySeconds: 15
        periodSeconds: 10
        failureThreshold: 3
        successThreshold: 1
      livenessProbe:
        tcpSocket:
          port: 80 
        initialDelaySeconds: 60
        periodSeconds: 10
        failureThreshold: 3
        successThreshold: 1     
      resources:
        limits:
          cpu: 100m
          memory: 240Mi
      requests:
        cpu: 50m
        memory: 120Mi
