apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
      startupProbe:
        exec:
          command:
            - cat
            - /tmp/startup_complete
        periodSeconds: 10
        failureThreshold: 30
        successThreshold: 1
      readinessProbe:
        exec:
          command:
            - cat
            - /tmp/ready
        initialDelaySeconds: 15
        periodSeconds: 10
        failureThreshold: 3
        successThreshold: 1
      livenessProbe:
        exec:
          command:
            - cat
            - /tmp/healthy
        initialDelaySeconds: 60
        periodSeconds: 10
        failureThreshold: 3
        successThreshold: 1
      resources:
        limits:
          cpu: 100m
          memory: 240Mi
      requests:
        cpu: 50m
        memory: 120Mi
