apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-daemonset
  namespace: web
spec:
  selector:
      matchLabels:
        app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: 'nginx'
          image: nginx:latest
          ports:
          - containerPort: 80
          resources:
            limits:
              cpu: 100m
              memory: 240Mi
            requests:
              cpu: 50m
              memory: 120Mi