apiVersion: v1
kind: Service
metadata:
  name: nginx-loadbalancer
spec:
  selector:
    app: nginx-app
  ports:
    - protocol: TCP
      port: 80 #local port
      targetPort: 80
  type: LoadBalancer