apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
      startupProbe:
        httpGet:
          path: /start
          port: 80
        periodSeconds: 5
        failureThreshold: 60
        successThreshold: 1
      resources:
        limits:
          cpu: 100m
          memory: 240Mi